server:
  port: 8080

logging:
  level:
    io:
      kimmking:
        cache : info

# 作业，在这里使用spring boot配置各项内容，
spring:
  redis:
    sentinel:
      master: mymaster
      nodes: localhost:26379,localhost:26380